version: "3"
services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    environment:
      FIREBASE_FIRESTORE_EMULATOR_ADDRESS: firestore:8080
  firestore:
    build: ./docker/firestore
    ports:
      - 8080:8080
